version: "3.8"

services:
    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_DB: mydb
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        networks:
            - private

    api:
        build: ./template
        container_name: api
        ports:
            - "8080:8080"
        depends_on:
            - postgres
        networks:
            - public
            - private

    frontend:
        build: ./client
        container_name: client
        ports:
            - "5173:5173"
        depends_on:
            - api
            - postgres
        networks:
            - public

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_LISTEN_PORT: 80
        ports:
            - "15432:80"
        networks:
            - private
            - public

networks:
    public:
    private:
